version: '3'

networks:
  nt-exam:
    driver: bridge

services:
  exam_api:
    image: exam_api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=examdb;username=devuser;password=devpassword"
    networks:
      - nt-exam

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "devuser"
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_DB: "examdb"
    networks:
      - nt-exam
volumes:
  db_volume:
